---
- name: Ensure configuration directory exists
  ansible.builtin.file:
    name: "{{ bigfix_client_conf_dir }}"
    mode: "0755"
    state: directory

- name: Download the BigFix Client
  ansible.builtin.get_url:
    url: "{{ bigfix_client_file_url }}"
    dest: "/tmp/{{ bigfix_client_file_dest }}"
    checksum: "sha256:{{ bigfix_client_file_sum }}"
    mode: "0644"

- name: Include the OS specific installation procedure
  ansible.builtin.include_tasks: "install/{{ ansible_os_family }}.yml"

- name: Record the installation
  ansible.builtin.file:
    dest: "{{ bigfix_client_conf_dir }}/.ansible_installed"
    mode: "0644"
    state: touch
