---

- name: Load OS specific vars
  ansible.builtin.include_vars: "{{ ansible_distribution }}-{{ __bigfix_ansible_distro_arch }}.yml"

- name: Load OS Family specific vars
  when: bigfix_client_file_sum is not defined
  ansible.builtin.include_vars: "{{ ansible_os_family }}-{{ __bigfix_ansible_distro_arch }}.yml"

- name: Failing due to undetermined OS
  ansible.builtin.fail:
    msg: OS could not be determined.
  when: bigfix_client_file_sum is not defined

- name: Check for BigFix
  ansible.builtin.stat:
    path: "{{ bigfix_client_conf_dir }}/.ansible_installed"
  register: bigfix_installed

- name: Install
  when: not bigfix_installed.stat.exists or bigfix_update is defined
  ansible.builtin.include_tasks: install.yml

- name: Determine if masthead already exists
  ansible.builtin.stat:
    path: "{{ bigfix_client_conf_dir }}/actionsite.afxm"
  register: masthead_file

- name: Download masthead from BigFix Server
  when: not masthead_file.stat.exists
  ansible.builtin.get_url:
    url: "{{ bigfix_client_masthead_url }}"
    dest: "{{ bigfix_client_conf_dir }}/actionsite.afxm"
    mode: "644"
  notify:
    - Restart bigfix-client
