---
- name: Converge
  hosts: all:!nginx
  vars:
    bigfix_client_server_name: nginx
    bigfix_client_server_port: 80
    bigfix_client_server_validate_certs: false
  roles:
    - outsideopen.bigfix_client
