---
- name: Converge - masthead server
  hosts: nginx
  gather_facts: false
  tasks:
    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
        update_cache: true

    - name: Copy the debug masthead
      ansible.builtin.copy: # noqa: risky-file-permissions
        src: masthead/
        dest: /usr/share/nginx/html/masthead

    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted

- name: Converge
  hosts: all:!nginx
  vars:
    bigfix_client_server_name: 172.17.0.2
    bigfix_client_server_port: 80
  roles:
    - outsideopen.bigfix_client
