---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: nginx
    image: nginx
  - name: "bigfix-client-${image:-amazonlinux}-${tag:-latest}${TOX_ENVNAME}"
    image: "${namespace:-robertdebock}/${image:-amazonlinux}:${tag:-latest}"
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
      bin_ansible_callbacks: true
scenario:
  name: default
verifier:
  name: ansible
