---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: nginx
    image: nginx:mainline-alpine-slim
  - name: "bigfix-client-${MOLECULE_DISTRO:-ubuntu2204}-${tag:-latest}${TOX_ENVNAME}"
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2204}-ansible:latest"
    privileged: true
    pre_build_image: true
    cgroupns_mode: host
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /run
      - /run/lock
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
      bin_ansible_callbacks: true
scenario:
  name: default
verifier:
  name: ansible
