---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: nginx
    image: nginx:mainline-alpine-slim
    command: nginx -g 'daemon off;'
    volumes:
      - ${PWD}/molecule/default/files/masthead:/usr/share/nginx/html/masthead
      - ${PWD}/molecule/default/files/masthead/masthead.afxm:/usr/share/nginx/html/masthead/masthead.afxm
  - name: "bigfix-client-${image:-ubuntu2204}-${tag:-latest}${TOX_ENVNAME}"
    image: "geerlingguy/docker-${image:-ubuntu2204}-ansible:latest"
    privileged: true
    pre_build_image: true
    cgroupns_mode: host
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /run
      - /run/lock
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
      bin_ansible_callbacks: true
scenario:
  name: default
verifier:
  name: ansible
