---
name: Ansible Molecule
on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    tags_ignore:
      - '*'
  pull_request:
  schedule:
    - cron: '28 15 13 * *'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: molecule
        uses: ansible/ansible-lint@main
  test:
    needs:
      - lint
    runs-on: robertdebock/github-action-molecule:6.0.1
    strategy:
      fail-fast: false
      matrix:
        config:
          - image: amazonlinux2
          - image: ubuntu2204
          - image: rockylinux8
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          path: "${{ github.repository }}"
      - name: molecule
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          image: ${{ matrix.image }}
