---
name: Ansible Molecule
on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    tags_ignore:
      - '*'
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ansible/ansible-lint@main
  test:
    needs:
      - lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          # current gen
          - ubuntu2404
          # previous gen
          - ubuntu2204
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          path: "${{ github.repository }}"

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install test dependencies
        run: pip install molecule-docker ${{ matrix.reqs }}

      - name: create docker network for molecule
        run: docker network create molecule

      - name: molecule
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          image: "${{ matrix.image }}"
        working-directory: "${{ github.repository }}"
